### ISSUE TITLE
This is an issue.

### ISSUE THREAD

**Issue by askaydevs** [sarvpriy/coinswitch#1]
This is a comment on the issue.

**Comment by sarvpriy** [comment]
This is a reply to the comment on the issue.

**Comment by askaydevs** [comment]
Your reply to the comment on the issue does not resolve the issue.

**Comment by sarvpriy** [comment]
It is as per the design and the discussion and already tested. However still you can do r&d and propose some solution.

**Comment by askaydevs** [comment]
I have a solution in mind. I would propose to close the issue. What are your views mate?

**Comment by sarvpriy** [comment]
Ok then, raise a PR. I'll look into it.
